name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-artifact-and-docker-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build and test application
      run: ./gradlew build
      
    - name: Build Docker image
      run: docker build -t gcp-ip-ranges-api:latest .
